import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  type Relation,
} from 'typeorm';
import { School } from '../../tenant/school.entity';
import { Student } from '../../students/entities/student.entity';

export type AttendanceStatus = 'present' | 'absent' | 'excused' | 'late';

export const ATTENDANCE_STATUSES: AttendanceStatus[] = [
  'present',
  'absent',
  'excused',
  'late',
];

/** تقييم الأخلاق — behaviour/manners score, 1 (worst) … 5 (best). */
export const ETHICS_RATING_MIN = 1;
export const ETHICS_RATING_MAX = 5;
export const ETHICS_RATING_DEFAULT = 5;

/**
 * One row per (student, date) regardless of how many halaqat the student is in.
 *
 * Model is "present by default": the midnight seed cron pre-creates a `present`
 * row for every obligated student, and teachers then mark the exceptions
 * (absent / excused / late) by correcting that row. A seeded row has
 * `recorded_by = NULL`; a human correction sets `modified_by` + `original_status`.
 *
 * `ethics_rating` (تقييم الأخلاق) follows the same shape: seeded rows carry the
 * default 5 and teachers lower it only where warranted.
 */
@Entity('student_attendances')
@Index('uk_sa_student_date', ['studentId', 'attendanceDate'], { unique: true })
@Index('uk_sa_client', ['clientUuid'], { unique: true })
@Index('idx_sa_school_date', ['schoolId', 'attendanceDate'])
@Index('idx_sa_status', ['status'])
export class StudentAttendance {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id!: number;

  @Column({ name: 'school_id', type: 'int' })
  schoolId!: number;

  @Column({ name: 'student_id', type: 'int' })
  studentId!: number;

  @Column({ name: 'attendance_date', type: 'date' })
  attendanceDate!: string;

  @Column({
    type: 'enum',
    enum: ATTENDANCE_STATUSES,
    default: 'present',
  })
  status!: AttendanceStatus;

  /**
   * تقييم الأخلاق — behaviour score for the day, 1..5. Follows the same
   * "default then correct" model as `status`: the seed cron leaves it at the
   * column default (5) and teachers lower it for the exceptions.
   */
  @Column({
    name: 'ethics_rating',
    type: 'tinyint',
    unsigned: true,
    default: ETHICS_RATING_DEFAULT,
  })
  ethicsRating!: number;

  @Column({ name: 'excuse_note', type: 'text', nullable: true })
  excuseNote!: string | null;

  /**
   * ملاحظة المحفّظ اليومية — free-text teacher note for the daily evaluation
   * report (§22). Distinct from `excuse_note` (absence reason) and
   * `modification_reason` (audit of a correction). A snapshot of this value is
   * copied into the saved report row so historical reports stay immutable.
   */
  @Column({ name: 'daily_note', type: 'text', nullable: true })
  dailyNote!: string | null;

  /** NULL = auto-generated by the seed cron; otherwise the user who recorded it. */
  @Column({ name: 'recorded_by', type: 'int', nullable: true })
  recordedBy!: number | null;

  @CreateDateColumn({ name: 'recorded_at', type: 'datetime', precision: 6 })
  recordedAt!: Date;

  @Column({ name: 'client_uuid', type: 'char', length: 36, nullable: true })
  clientUuid!: string | null;

  @Column({
    name: 'client_recorded_at',
    type: 'datetime',
    precision: 6,
    nullable: true,
  })
  clientRecordedAt!: Date | null;

  @Column({ name: 'device_id', type: 'varchar', length: 64, nullable: true })
  deviceId!: string | null;

  @Column({ name: 'modified_by', type: 'int', nullable: true })
  modifiedBy!: number | null;

  @Column({
    name: 'modified_at',
    type: 'datetime',
    precision: 6,
    nullable: true,
  })
  modifiedAt!: Date | null;

  @Column({ name: 'modification_reason', type: 'text', nullable: true })
  modificationReason!: string | null;

  @Column({
    name: 'original_status',
    type: 'varchar',
    length: 20,
    nullable: true,
  })
  originalStatus!: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'datetime', precision: 6 })
  createdAt!: Date;

  @ManyToOne(() => School, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'school_id' })
  school!: Relation<School>;

  @ManyToOne(() => Student, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'student_id' })
  student!: Relation<Student>;
}
