import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { School } from '../../tenant/school.entity';
import { User } from '../../users/entities/user.entity';
import {
  ATTENDANCE_STATUSES,
  type AttendanceStatus,
} from './student-attendance.entity';

/**
 * Attendance for staff (teachers + admins → `users`). One row per (user, date).
 * Same "present by default" model and offline-sync fields as student attendance.
 */
@Entity('teacher_attendances')
@Index('uk_ta_user_date', ['userId', 'attendanceDate'], { unique: true })
@Index('uk_ta_client', ['clientUuid'], { unique: true })
@Index('idx_ta_school_date', ['schoolId', 'attendanceDate'])
@Index('idx_ta_status', ['status'])
export class TeacherAttendance {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id!: number;

  @Column({ name: 'school_id', type: 'int' })
  schoolId!: number;

  @Column({ name: 'user_id', type: 'int' })
  userId!: number;

  @Column({ name: 'attendance_date', type: 'date' })
  attendanceDate!: string;

  @Column({
    type: 'enum',
    enum: ATTENDANCE_STATUSES,
    default: 'present',
  })
  status!: AttendanceStatus;

  @Column({ name: 'excuse_note', type: 'text', nullable: true })
  excuseNote!: string | null;

  /** NULL = auto-generated by the seed cron; otherwise the user who recorded it. */
  @Column({ name: 'recorded_by', type: 'int', nullable: true })
  recordedBy!: number | null;

  @CreateDateColumn({ name: 'recorded_at', type: 'datetime', precision: 6 })
  recordedAt!: Date;

  @Column({ name: 'client_uuid', type: 'char', length: 36, nullable: true })
  clientUuid!: string | null;

  @Column({
    name: 'client_recorded_at',
    type: 'datetime',
    precision: 6,
    nullable: true,
  })
  clientRecordedAt!: Date | null;

  @Column({ name: 'device_id', type: 'varchar', length: 64, nullable: true })
  deviceId!: string | null;

  @Column({ name: 'modified_by', type: 'int', nullable: true })
  modifiedBy!: number | null;

  @Column({
    name: 'modified_at',
    type: 'datetime',
    precision: 6,
    nullable: true,
  })
  modifiedAt!: Date | null;

  @Column({ name: 'modification_reason', type: 'text', nullable: true })
  modificationReason!: string | null;

  @Column({
    name: 'original_status',
    type: 'varchar',
    length: 20,
    nullable: true,
  })
  originalStatus!: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'datetime', precision: 6 })
  createdAt!: Date;

  @ManyToOne(() => School, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'school_id' })
  school!: School;

  @ManyToOne(() => User, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'user_id' })
  user!: User;
}
